machine: chadoq3
qpu_generator:
  type: EdgeGadgetQPUGenerator
  back_converter: EdgeGadgetBackConverter
  args:
    weights_detuning_fraction: 0.1
    atomic_min_distance: 4
    length_ratio: 2
rydberg_correction_factor: 1.01
time: 10000 # ns
adiabatic_waveform:
  detunings:
    detuning_min: -20
    detuning_max: 40
    detuning_base: 0