machine: chadoq3
qpu_generator:
  type: EdgeGadgetQPUGenerator
  args:
    weights_detuning_fraction: 0.9
    x: 0
    y: 0
    z: 0
    w: 0
    b: 0.8
    atomic_min_distance: 3.8
    length_ratio: 2
rydberg_correction_factor: 1.01
time: 10000 # ns
adiabatic_waveform:
  detunings:
    detuning_min: -20
    detuning_max: 50
    detuning_base: 0